-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REV.REVIEW_SCORE),2) AS SCORE FROM REST_INFO INFO
JOIN REST_REVIEW REV ON INFO.REST_ID = REV.REST_ID
WHERE INFO.ADDRESS LIKE ('서울%')
GROUP BY REV.REST_ID
ORDER BY 6 DESC, 4 DESC;