-- 코드를 입력하세요
SELECT CAR_TYPE, COUNT(CAR_ID) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE CONCAT('%','통풍시트','%')
OR OPTIONS LIKE CONCAT('%','열선시트','%')
OR OPTIONS LIKE CONCAT('%','가죽시트','%')
GROUP BY CAR_TYPE
ORDER BY 1
# WHERE