-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT FH.FLAVOR FROM FIRST_HALF FH, JULY J
    WHERE FH.FLAVOR = J.FLAVOR
    GROUP BY FH.FLAVOR
    ORDER BY SUM(FH.TOTAL_ORDER + J.TOTAL_ORDER) DESC
)
WHERE ROWNUM <= 3;