-- 코드를 입력하세요
# SELECT F.FLAVOR FROM FIRST_HALF AS F
# JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
# GROUP BY F.FLAVOR
# ORDER BY (F.TOTAL_ORDER + SUM(J.TOTAL_ORDER)) DESC
# LIMIT 3

SELECT A.FLAVOR
FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY
     ) A
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) DESC
LIMIT 3